# Server
server:
  port: '8080'
  # Spring Boot Configuration
spring:
  jpa.database: 'POSTGRESQL'
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    platform: 'postgres'
    username: 'postgres'
    password: 'postgres'
  # Swagger
springdoc.swagger-ui.path: '/swagger-ui.html'
# App data info
app.info:
  name: 'FoodTracker'
  version: '1.0'
  description: 'Application dedicated to managing a food in database. So that the food does not spoil in the fridge.'
